"""add column

Revision ID: d2e74c750757
Revises: 8595e36219eb
Create Date: 2025-08-02 17:20:08.096429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e74c750757'
down_revision: Union[str, Sequence[str], None] = '8595e36219eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrow_sets', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('arrows', sa.Column('spot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arrows', 'spot')
    op.drop_column('arrow_sets', 'timestamp')
    # ### end Alembic commands ###
